import { createConstants } from '../utils';

export default createConstants(
  // Map
  'UPDATE_MAP_CENTER_REQUEST',
  'UPDATE_MAP_CENTER_SUCCESS',
  'UPDATE_MAP_CENTER_FAIL',

  'LOAD_MAP_REQUEST',
  'LOAD_MAP_SUCCESS',
  'LOAD_MAP_FAIL',

  'LOAD_ADJACENCY_LIST_REQUEST',
  'LOAD_ADJACENCY_LIST_SUCCESS',
  'LOAD_ADJACENCY_LIST_FAIL',

  'CALCULATE_ROUTE_REQUEST',
  'CALCULATE_ROUTE_SUCCESS',
  'CALCULATE_ROUTE_FAIL',

  'SELECT_START_STOP_REQUEST',
  'SELECT_START_STOP_SUCCESS',
  'SELECT_START_STOP_FAIL',

  'SELECT_END_STOP_REQUEST',
  'SELECT_END_STOP_SUCCESS',
  'SELECT_END_STOP_FAIL',

  'DRAW_POLYLINES_REQUEST',
  'DRAW_POLYLINES_SUCCESS',
  'DRAW_POLYLINES_FAIL',

  'CLEAR_POLYLINES_REQUEST',
  'CLEAR_POLYLINES_SUCCESS',
  'CLEAR_POLYLINES_FAIL',

  'SELECT_BUS_SERVICE_REQUEST',
  'SELECT_BUS_SERVICE_SUCCESS',
  'SELECT_BUS_SERVICE_FAIL',

  'TOGGLE_BUS_SERVICE_REQUEST',
  'TOGGLE_BUS_SERVICE_SUCCESS',
  'TOGGLE_BUS_SERVICE_FAIL',

  'SELECT_START_STOP',
  'SELECT_END_STOP',
  'SELECT_START_END_STOP',


  'LOAD_ALL_BUS_STOPS',

  'LOAD_ALL_BUS_SERVICES',

  'DRAW_ROUTE',
  'SHOW_JOURNEY',

  );
