import { createConstants } from '../utils';

export default createConstants(
  // General
  'REQUEST_FAIL',
  'MODAL_SHOW',
  'MODAL_HIDE',

  // Map
  'PLACES_CHANGED',
  'UPDATE_MAP_CENTER',
  'AJACENCY_LIST_LOADED',
  'ON_MAP_LOAD',

  'PLACES_CHANGED_REQUEST',
  'PLACES_CHANGED_SUCCESS',
  'PLACES_CHANGED_FAIL',

  'UPDATE_MAP_CENTER_REQUEST',
  'UPDATE_MAP_CENTER_SUCCESS',
  'UPDATE_MAP_CENTER_FAIL',

  'MAP_LOAD_REQUEST',
  'MAP_LOAD_SUCCESS',
  'MAP_LOAD_FAIL',

  'AJACENCY_LOAD_REQUEST',
  'AJACENCY_LOAD_SUCCESS',
  'AJACENCY_LOAD_FAIL',

  'CALCULATE_ROUTE_REQUEST',
  'CALCULATE_ROUTE_SUCCESS',
  'CALCULATE_ROUTE_FAIL',

  'SELECT_START_STOP_REQUEST',
  'SELECT_START_STOP_SUCCESS',
  'SELECT_START_STOP_FAIL',

  'SELECT_END_STOP_REQUEST',
  'SELECT_END_STOP_SUCCESS',
  'SELECT_END_STOP_FAIL',

  'DRAW_POLYLINES_REQUEST',
  'DRAW_POLYLINES_SUCCESS',
  'DRAW_POLYLINES_FAIL',

  'DRAW_ROUTE',
  'SHOW_JOURNEY',

  'SELECT_START_STOP',
  'SELECT_END_STOP',
  'SELECT_START_END_STOP',

  'LOAD_ALL_BUS_STOPS',

  'LOAD_ALL_BUS_SERVICES',
  );
